# Generated by Django 2.2.4 on 2020-05-08 04:57

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp1_intro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='num_questions',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
