# Generated by Django 2.2.4 on 2020-05-08 05:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp1_intro', '0002_subsession_num_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sooner_period',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='treatment_method',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='waiting_period',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
