# Generated by Django 2.2.4 on 2020-05-10 08:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp1_intro', '0003_auto_20200508_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='switch_point',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='請選擇您的轉換點'),
        ),
    ]
