# Generated by Django 2.2.4 on 2020-05-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exp1_questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gained_amount',
        ),
    ]
