# Generated by Django 2.2.4 on 2020-05-07 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exp1_questionnaire', '0003_player_gained_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gained_amount',
        ),
    ]
