# Generated by Django 2.2.4 on 2020-05-07 04:38

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp1_questionnaire', '0004_remove_player_gained_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sooner_period',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
