# Generated by Django 2.2.4 on 2020-05-07 04:40

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exp1_questionnaire', '0005_player_sooner_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sooner_period',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
